name: picohttpparser
description: Dart FFI bindings to picohttpparser.
version: 0.0.2
repository: https://github.com/ykmnkmi/picohttpparser.dart

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3
  logging: ^1.3.0
  native_assets_cli: ^0.9.0
  native_toolchain_c: ^0.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.10
